<?php

global $exts;
global $constStr;

$exts['img'] = ['ico', 'bmp', 'gif', 'jpg', 'jpeg', 'jpe', 'jfif', 'tif', 'tiff', 'png', 'heic', 'webp'];
$exts['music'] = ['mp3', 'wma', 'flac', 'ape', 'wav', 'ogg', 'm4a'];
$exts['office'] = ['doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx'];
$exts['txt'] = ['txt', 'bat', 'sh', 'php', 'asp', 'js', 'css', 'json', 'html', 'c', 'cpp', 'md', 'py', 'omf'];
$exts['video'] = ['mp4', 'webm', 'mkv', 'mov', 'flv', 'blv', 'avi', 'wmv', 'm3u8', 'rm', 'rmvb'];
$exts['zip'] = ['zip', 'rar', '7z', 'gz', 'tar'];

$constStr = [
    'languages' => [
        'en-us' => 'English',
        'zh-cn' => '簡體中文',
        'ja' => '日本語',
        'ko-kr' => '한국어',
        'fa' => 'فارسی',
    ],
    'Week' => [
        'en-us' => [
            0 => 'Sunday',
            1 => 'Monday',
            2 => 'Tuesday',
            3 => 'Wednesday',
            4 => 'Thursday',
            5 => 'Friday',
            6 => 'Saturday',
        ],
        'zh-cn' => [
            0 => '星期日',
            1 => '星期一',
            2 => '星期二',
            3 => '星期三',
            4 => '星期四',
            5 => '星期五',
            6 => '星期六',
        ],
        'ja' => [
            0 => '日曜日',
            1 => '月曜日',
            2 => '火曜日',
            3 => '水曜日',
            4 => '木曜日',
            5 => '金曜日',
            6 => '土曜日',
        ],
        'ko-kr' => [
            0 => '일요일',
            1 => '월요일',
            2 => '화요일',
            3 => '수요일',
            4 => '목요일',
            5 => '금요일',
            6 => '토요일',
        ],
        'fa' => [
            0 => 'یکشنبه',
            1 => 'دوشنبه',
            2 => 'سه شنبه',
            3 => 'چهارشنبه',
            4 => 'پنج شنبه',
            5 => 'جمعه',
            6 => 'شنبه',
        ],
    ],
    'EnvironmentsDescription' => [
        'en-us' => [
            'admin' => 'The admin password, Login button will not show when empty',
            'adminloginpage' => 'if set, the Login button will not display, and the login page no longer \'?admin\', it is \'?{this value}\'.',
            'customScript' => '<script> in all pages, e.g. http turn to https',
            'customCss' => '<style> in <head>',
            'customTheme' => 'an url of html',
            'domain_path' => 'more custom domain, format is a1.com:/dirto/path1|b2.com:/path2',
            'diskname' => 'The disk name you want show.',
            'disktag' => 'A tag used in store config and url.',
            'disableShowThumb' => 'if 1, the ShowThumbnail button will not display',
            'disableChangeTheme' => 'if 1, the Theme selection button will not display',
            'downloadencrypt' => '0 or 1. if 1, the files in encrypt folder can be downloaded without password',
            'background' => 'Set an url as background photo.',
            'backgroundm' => 'Set an url as background in mobile phone.',
            'theme' => 'Select theme.',
            'timezone' => 'Set default timezone.',
            'guestup_path' => 'Set guest upload dir, before set this, the files in this dir will show as normal.',
            'hideFunctionalityFile' => '0 or 1. if 1, some file will not show in list to guest, like readme.md',
            'passfile' => 'The password of folder(& its childrens) will save in this file.',
            'domainforproxy' => 'Will replace the https://xxxxx-my.sharepoint.com with this value.Add &Origindomain=xxxxx-my.sharepoint.com at last',
            'public_path' => 'Show this Onedrive dir when through the long url of API Gateway; public show files less than private.',
            'sitename' => 'sitename',
            'Onedrive_ver' => 'Onedrive version',
        ],
        'zh-cn' => [
            'admin' => '管理密碼，不添加時不顯示登入頁面且無法登入。',
            'adminloginpage' => '如果設置，登入按鈕及頁面隐藏。管理登入的頁面不再是\'?admin\'，而是\'?此設置的值\'。',
            'customScript' => '<script>，在所有頁都會存在,例如放一個http跳轉https',
            'customCss' => '<style>，在<head>最後面',
            'customTheme' => 'html格式的主題的url',
            'domain_path' => '使用多個自定義域名時，指定每個域名看到的目錄。格式爲a1.com:/dirto/path1|b1.com:/path2，比private_path優先。',
            'diskname' => '這個盤你想顯示什麽名稱。',
            'disktag' => '一個標簽，用於保存配置，多盤時會顯示在url中。',
            'disableShowThumb' => '如果填 1, ‘顯示縮略’按鈕将被隐藏。',
            'disableChangeTheme' => '如果填 1, 主題選擇切換将被隐藏',
            'downloadencrypt' => '0 或 1。如果 1, 那加密目錄内的文件可以不需要密碼就能下載。',
            'background' => '設置一個url作爲背景。',
            'backgroundm' => '設置一個url作爲手機用的背景。',
            'theme' => '選擇一個主題。',
            'timezone' => '設置預設時區。',
            'guestup_path' => '設置遊客上傳路徑（圖床路徑），不設置這個值時該目錄内容會正常列文件出來，設置後只有上傳界面，不顯示其中文件（登入後顯示）。',
            'hideFunctionalityFile' => '0 或 1。如果 1, 某些文件不清單給遊客看，但它的功能正常，比如readme.md',
            'passfile' => '自定義密碼文件的名字，可以是\'pppppp\'，也可以是\'aaaa.txt\'等等；列目錄時不會顯示，只有知道密碼才能檢視或下載此文件。密碼是這個文件的内容，可以空格、可以中文；',
            'domainforproxy' => '會将https://xxxxx-my.sharepoint.com替換成這個值，在目標需要自己設置反代。會加上&Origindomain=原域名',
            'public_path' => '使用API長連結訪問時，顯示網盤文件的路徑，不設置時預設爲根目錄；不能是private_path的上級（public看到的不能比private多，要麽看到的就不一樣）。',
            'sitename' => '網站的名稱',
            'Onedrive_ver' => 'Onedrive版本',
        ],
        'ja' => [
            'admin' => 'パスワードを管理する、追加しない場合、ログインページは表示されず、ログインできません。',
            'adminloginpage' => '設定すると、ログインボタンとページが非表示になります。ログインを管理するためのページは\'?admin \'ではなく、\'?この設定の値\'。',
            'domain_path' => '複數のカスタムドメイン名を使用する場合、各ドメイン名に表示されるディレクトリを指定します。形式はa1.com:/dirto/path1|b1.com:/path2で、private_pathよりも優先されます。',
            'diskname' => '',
            'disktag' => '',
            'downloadencrypt' => '',
            'background' => '',
            'guestup_path' => 'マップベッドのパスを設定します。この値が設定されていない場合、ディレクトリの内容は通常ファイルにリストされ、設定後はアップロードインターフェイスのみが表示されます。',
            'passfile' => 'カスタムパスワードファイルの名前は、\'pppppp \'、\'aaaa.txt \'などの場合があります。ディレクトリをリストするときには表示されません。パスワードを知っている場合にのみ、このファイルを表示またはダウンロードできます。 パスワードはこのファイルの内容であり、スペースまたは漢字を使用できます。',
            'public_path' => 'APIのロングリンクアクセスを使用する場合、ネットワークディスクファイルのパスが表示されますが、設定されていない場合はデフォルトでルートディレクトリになり、private_pathの上位にはなりません（publicはprivate以上のものを見ることができません。それ以外は異なります。）。',
            'sitename' => 'ウェブサイト名',
            'Onedrive_ver' => 'Onedriveバージョン',
        ],
        'ko-kr' => [
            'admin' => '비밀번호를 관리하고 로그인 페이지를 표시하지 않으며 추가하지 않으면 로그인 할 수 없습니다.',
            'adminloginpage' => '설정하면 로그인 버튼과 페이지가 숨겨집니다. 로그인 관리 페이지는 더 이상 \ ?Admin\'이 아니라 \ ?이 설정의 값 \'입니다.',
            'domain_path' => '여러 개의 사용자 정의 도메인 이름을 사용하는 경우 각 도메인 이름에 표시되는 디렉토리를 지정하십시오. 형식은 a1.com:/dirto/path1|b1.com:/path2이며 private_path보다 우선합니다.',
            'diskname' => '이 디스크에 어떤 이름을 표시 하시겠습니까?',
            'disktag' => '레이블은 구성을 저장하는 데 사용되며 디스크가 여러 개인 경우 URL에 표시됩니다.',
            'downloadencrypt' => '',
            'background' => 'URL을 배경으로 설정하거나 표시하는.',
            'guestup_path' => '방문자의 업로드 경로 (맵 베드 경로)를 설정합니다.이 값을 설정하지 않으면 디렉토리의 내용이 파일로 표시되고 설정 후에는 업로드 인터페이스 만 표시되고 파일은 표시되지 않습니다 (로그인 후 표시).',
            'passfile' => '사용자 정의 비밀번호 파일의 이름은 \'pppppp\' \'aaaa.txt \'등이 될 수 있으며 디렉토리가 나열되어 있으면 표시되지 않으며 비밀번호를 알고있는 경우에만이 파일을 보거나 다운로드 할 수 있습니다. 암호는이 파일의 내용이며 공백이거나 한국어 일 수 있습니다.',
            'public_path' => 'API 긴 링크 액세스를 사용하는 경우 네트워크 디스크 파일의 경로가 표시됩니다. 설정되지 않은 경우 기본적으로 루트 디렉토리로 설정됩니다.',
            'sitename' => '웹 사이트 이름',
            'Onedrive_ver' => 'Onedrive 버전',
        ],
        'fa' => [
            'admin' => 'رمز عبور ادمین، در صورت خالی بودن دکمه لاگین به نمایش در نمی‌آید',
            'adminloginpage' => 'در صورت تنظیم ، دکمه ورود نمایش داده نمی شود و صفحه ورود دیگر \?admin\ نیست بلکه \?{مقدار ورودی شما}\ است.',
            'domain_path' => 'تنظیم دامنه سفارشی، به صورت a1.com:/dirto/path1|b2.com:/path2',
            'diskname' => 'نام دیسک که می‌خواهید نشان دهید.',
            'disktag' => 'تگی که در ذخیره پیکربندی و نشانی اینترنتی استفاده می‌شود.',
            'downloadencrypt' => '',
            'background' => 'تنظیم عکس پشت زمینه به صورت url یا قرار دادن بک گراند به صورت دستی در مسیر نشان داده شده.',
            'guestup_path' => 'قبل از تنظیم این گزینه ، فایل آپلود guest را تنظیم کنید ، پرونده های موجود در این حالت به صورت عادی نشان داده می شوند.',
            'passfile' => 'رمز عبور dir در این فایل ذخیره می شود.',
            'public_path' => 'این مسیر Onedrive را هنگامی که از طریق آدرس طولانی API Gateway استفاده می کنید ، نشان دهید. فایل های نمایش عمومی کمتر از خصوصی.',
            'sitename' => 'نام سایت',
            'Onedrive_ver' => 'ورژن Onedrive',
        ],
    ],
    'SetSecretsFirst' => [
        'en-us' => 'Set API in Config first! or reinstall.',
        'zh-cn' => '先在環境變量設置API！或重裝。',
        'ja' => '最初に環境変數にAPIを設定してください！',
        'ko-kr' => '먼저 환경 변수에서 API를 설정하십시오! 또는 다시 설치하십시오.',
        'fa' => 'ابتدا API را در پیکربندی تنظیم کنید! یا دوباره نصب کنید.',
    ],
    'RefreshtoLogin' => [
        'en-us' => '<font color="red">Refresh</font> and login.',
        'zh-cn' => '請<font color="red">重新整理</font>頁面後重新登入',
        'ja' => 'ページを<font color = "red">更新</font>して、再度ログインしてください',
        'ko-kr' => '페이지를 <font color = "red"> 새로 고침 </ font> 하시고 다시 로그인하십시오',
        'fa' => '<font color="red">رفرش</font> و لاگین.',
    ],
    'AdminLogin' => [
        'en-us' => 'Admin Login',
        'zh-cn' => '管理登入',
        'ja' => 'ログインを管理する',
        'ko-kr' => '로그인 관리',
        'fa' => 'ورود ادمین',
    ],
    'LoginSuccess' => [
        'en-us' => 'Login Success!',
        'zh-cn' => '登入成功，正在跳轉',
        'ja' => 'ログイン成功、ジャンプ',
        'ko-kr' => '로그인 성공, 점프',
        'fa' => 'ورود با موفقیت انجام شد!',
    ],
    'InputPassword' => [
        'en-us' => 'Input Password',
        'zh-cn' => '輸入密碼',
        'ja' => 'パスワードを入力してください',
        'ko-kr' => '비밀번호 입력',
        'fa' => 'رمز عبور را وارد کنید',
    ],
    'Login' => [
        'en-us' => 'Login',
        'zh-cn' => '登入',
        'ja' => 'サインイン',
        'ko-kr' => '로그인',
        'fa' => 'ورود',
    ],
    'Encrypt' => [
        'en-us' => 'Encrypt',
        'zh-cn' => '加密',
        'ja' => '暗號化',
        'ko-kr' => '암호화',
        'fa' => 'رمزگذاری',
    ],
    'SetpassfileBfEncrypt' => [
        'en-us' => 'Set \'passfile\' in Environments before encrypt',
        'zh-cn' => '先在環境變量設置passfile才能加密',
        'ja' => '最初に暗號化する環境変數にパスファイルを設定します',
        'ko-kr' => '암호화하기 전에 환경 변수에 패스 파일을 설정하십시오',
        'fa' => 'قبل از رمزگذاری \"pass file \" را در محیط تنظیم کنید',
    ],
    'updateProgram' => [
        'en-us' => 'Update Program',
        'zh-cn' => '一鍵更新',
        'ja' => 'ワンクリック更新',
        'ko-kr' => '원 클릭 업데이트',
        'fa' => 'برنامه را به روز کنید',
    ],
    'UpdateSuccess' => [
        'en-us' => 'Program update Success!',
        'zh-cn' => '程式升級成功！',
        'ja' => 'プログラムのアップグレードに成功しました！',
        'ko-kr' => '프로그램 업그레이드 성공!',
        'fa' => 'موفقیت به روز رسانی برنامه!',
    ],
    'Setup' => [
        'en-us' => 'Setup',
        'zh-cn' => '設置',
        'ja' => '設定する',
        'ko-kr' => '설정',
        'fa' => 'نصب',
    ],
    'Back' => [
        'en-us' => 'Back',
        'zh-cn' => '返回',
        'ja' => 'back',
        'ko-kr' => '돌아 가기',
        'fa' => 'بازگشت',
    ],
    'Theme' => [
        'en-us' => 'Theme',
        'zh-cn' => '主題',
    ],
    'NotNeedUpdate' => [
        'en-us' => 'Not Need Update',
        'zh-cn' => '不需要更新',
        'ja' => '更新不要',
        'ko-kr' => '업데이트가 필요하지 않습니다',
        'fa' => 'آپدیت لازم نیست',
    ],
    'PlatformConfig' => [
        'en-us' => 'Platform Config',
        'zh-cn' => '平台變量',
        'ja' => 'プラットフォーム変數',
        'ko-kr' => '플랫폼 변수',
        'fa' => 'پیکربندی پلتفرم',
    ],
    'DelDisk' => [
        'en-us' => 'Del This Disk',
        'zh-cn' => '删除此盤',
        'ja' => 'このディスクを削除',
        'ko-kr' => '이 디스크를 삭제',
        'fa' => 'پاک کردن این دیسک',
    ],
    'AddDisk' => [
        'en-us' => 'Add Onedrive Disk',
        'zh-cn' => '添加Onedrive槽',
        'ja' => 'Onedriveを追加',
        'ko-kr' => 'Onedrive 추가',
        'fa' => 'اضافه کردن دیسک Onedrive',
    ],
    'Home' => [
        'en-us' => 'Home',
        'zh-cn' => '首頁',
        'ja' => 'ホーム',
        'ko-kr' => '홈',
        'fa' => 'خانه',
    ],
    'Preview' => [
        'en-us' => 'Preview',
        'zh-cn' => '預覽',
    ],
    'List' => [
        'en-us' => 'List',
        'zh-cn' => '清單',
    ],
    'NeedUpdate' => [
        'en-us' => 'Program can update<br>Click setup in Operate at top.',
        'zh-cn' => '可以升級程式<br>在上方管理清單中<br>進入設置頁面升級',
        'ja' => 'プログラムをアップグレードできます<br>上記の管理メニューで<br>アップグレードする設定ページに入ります',
        'ko-kr' => '프로그램을 업그레이드 할 수 있습니다. <br> 위의 관리 메뉴에서 <br> 업그레이드 할 설정 페이지를 입력하십시오.',
        'fa' => 'برنامه می تواند آپدیت شود<br>روی گزینه نصب در بالای صفحه کلیک کنید.',
    ],
    'Operate' => [
        'en-us' => 'Operate',
        'zh-cn' => '管理',
        'ja' => '管理',
        'ko-kr' => '관리',
        'fa' => 'مدیریت',
    ],
    'Logout' => [
        'en-us' => 'Logout',
        'zh-cn' => '登出',
        'ja' => 'ログアウトする',
        'ko-kr' => '로그 아웃',
        'fa' => 'خروج',
    ],
    'Create' => [
        'en-us' => 'Create',
        'zh-cn' => '新建',
        'ja' => '新しい',
        'ko-kr' => '새로운',
        'fa' => 'ایجاد کردن',
    ],
    'Download' => [
        'en-us' => 'download',
        'zh-cn' => '下載',
        'ja' => 'ダウンロードする',
        'ko-kr' => '다운로드',
        'fa' => 'دانلود',
    ],
    'ClicktoEdit' => [
        'en-us' => 'Click to edit',
        'zh-cn' => '點擊後編輯',
        'ja' => 'クリック後に編集',
        'ko-kr' => '클릭 후 편집',
        'fa' => 'برای ویرایش کلیک کنید',
    ],
    'Save' => [
        'en-us' => 'Save',
        'zh-cn' => '保存',
        'ja' => '保存する',
        'ko-kr' => '저장',
        'fa' => 'ذخیره',
    ],
    'FileNotSupport' => [
        'en-us' => 'File not support preview.',
        'zh-cn' => '文件格式不支援預覽',
        'ja' => 'ファイル形式はプレビューをサポートしていません',
        'ko-kr' => '파일 형식은 미리보기를 지원하지 않습니다',
        'fa' => 'پیش نمایش برای این فایل پشتیبانی نمی شود.',
    ],
    'File' => [
        'en-us' => 'File',
        'zh-cn' => '文件',
        'ja' => 'ファイル',
        'ko-kr' => '파일',
        'fa' => 'فایل',
    ],
    'ShowThumbnails' => [
        'en-us' => 'Thumbnails',
        'zh-cn' => '圖片縮略',
        'ja' => '畫像のサムネイル',
        'ko-kr' => '사진 섬네일',
        'fa' => 'تصویر بندانگشتی',
    ],
    'OriginalPic' => [
        'en-us' => 'OriginalPic',
        'zh-cn' => '原圖',
    ],
    'CopyAllDownloadUrl' => [
        'en-us' => 'CopyAllDownloadUrl',
        'zh-cn' => '複制所有下載連結',
        'ja' => 'すべてのダウンロードリンクをコピー',
        'ko-kr' => '모든 다운로드 링크 복사',
        'fa' => 'کپی از تمام لینک ها',
    ],
    'Search' => [
        'en-us' => 'Search',
        'zh-cn' => '搜索',
    ],
    'EditTime' => [
        'en-us' => 'EditTime',
        'zh-cn' => '修改時間',
        'ja' => '変更時間',
        'ko-kr' => '수정 시간',
        'fa' => 'زمان ویرایش',
    ],
    'Size' => [
        'en-us' => 'Size',
        'zh-cn' => '大小',
        'ja' => 'サイズ ',
        'ko-kr' => '사이즈',
        'fa' => 'سایز',
    ],
    'Rename' => [
        'en-us' => 'Rename',
        'zh-cn' => '重命名',
        'ja' => '名前を変更',
        'ko-kr' => '이름 바꾸기',
        'fa' => 'تغییر نام',
    ],
    'Move' => [
        'en-us' => 'Move',
        'zh-cn' => ' ',
        'ja' => ' する',
        'ko-kr' => '이동',
        'fa' => 'انتقال',
    ],
    'Copy' => [
        'en-us' => 'Copy',
        'zh-cn' => '複制',
        'ja' => 'コピー',
        'ko-kr' => '복사',
        'fa' => 'کپی',
    ],
    'CannotMove' => [
        'en-us' => 'Can not Move!',
        'zh-cn' => '不能 ！',
        'ja' => '動かない！',
        'ko-kr' => '움직일 수 없어!',
        'fa' => 'نمی‌تواند منتقل شود!',
    ],
    'Delete' => [
        'en-us' => 'Delete',
        'zh-cn' => '删除',
        'ja' => '削除する',
        'ko-kr' => '삭제',
        'fa' => 'حذف کردن',
    ],
    'PrePage' => [
        'en-us' => 'PrePage',
        'zh-cn' => '上一頁',
        'ja' => '前へ',
        'ko-kr' => '이전',
        'fa' => 'صفحه قبل',
    ],
    'NextPage' => [
        'en-us' => 'NextPage',
        'zh-cn' => '下一頁',
        'ja' => '次のページ',
        'ko-kr' => '다음 페이지',
        'fa' => 'صفحه بعد',
    ],
    'Upload' => [
        'en-us' => 'Upload',
        'zh-cn' => '上傳',
        'ja' => 'アップロードする',
        'ko-kr' => '업로드',
        'fa' => 'آپلود',
    ],
    'UploadFile' => [
        'en-us' => 'Upload File(s)',
        'zh-cn' => '上傳文件',
    ],
    'UploadFolder' => [
        'en-us' => 'Upload Folder',
        'zh-cn' => '上傳文件夾',
    ],
    'FileSelected' => [
        'en-us' => 'Select File',
        'zh-cn' => '選擇文件',
        'ja' => 'ファイルを選択',
        'ko-kr' => '파일 선택',
        'fa' => 'انتخاب فایل',
    ],
    'NoFileSelected' => [
        'en-us' => 'Not Select File',
        'zh-cn' => '沒有選擇文件',
        'ja' => 'ファイルが選択されていません',
        'ko-kr' => '선택된 파일이 없습니다',
        'fa' => 'فایل را انتخاب نکنید',
    ],
    'Submit' => [
        'en-us' => 'Submit',
        'zh-cn' => '确認',
        'ja' => '確認する',
        'ko-kr' => '확인',
        'fa' => 'ارسال',
    ],
    'Close' => [
        'en-us' => 'Close',
        'zh-cn' => '關閉',
        'ja' => '閉じる',
        'ko-kr' => '닫기',
        'fa' => 'بستن',
    ],
    'InputPasswordUWant' => [
        'en-us' => 'Input Password you Want',
        'zh-cn' => '輸入想要設置的密碼',
        'ja' => '設定するパスワードを入力してください',
        'ko-kr' => '설정하려는 비밀번호를 입력하십시오',
        'fa' => 'پسورد خود را وارد کنید',
    ],
    'ParentDir' => [
        'en-us' => 'Parent Dir',
        'zh-cn' => '上一級目錄',
        'ja' => '親ディレクトリ',
        'ko-kr' => '부모 디렉토리',
        'fa' => 'مسیر',
    ],
    'Folder' => [
        'en-us' => 'Folder',
        'zh-cn' => '文件夾',
        'ja' => 'フォルダー',
        'ko-kr' => '폴더',
        'fa' => 'پوشه',
    ],
    'Name' => [
        'en-us' => 'Name',
        'zh-cn' => '名稱',
        'ja' => '名前',
        'ko-kr' => '이름',
        'fa' => 'نام',
    ],
    'Content' => [
        'en-us' => 'Content',
        'zh-cn' => '内容',
        'ja' => '内容',
        'ko-kr' => '내용',
        'fa' => 'محتوا',
    ],
    'CancelEdit' => [
        'en-us' => 'Cancel Edit',
        'zh-cn' => '取消編輯',
        'ja' => '編集をキャンセル',
        'ko-kr' => '편집 취소',
        'fa' => 'لغو ویرایش',
    ],
    'GetFileNameFail' => [
        'en-us' => 'Fail to Get File Name!',
        'zh-cn' => '獲取文件名失敗！',
        'ja' => 'ファイル名を取得できませんでした！',
        'ko-kr' => '파일 이름을 가져 오지 못했습니다!',
        'fa' => 'نام فایل به دست نیامد!',
    ],
    'GetUploadLink' => [
        'en-us' => 'Get Upload Link',
        'zh-cn' => '獲取上傳連結',
        'ja' => 'アップロードリンクを取得',
        'ko-kr' => '업로드 링크 받기',
        'fa' => 'دریافت لینک آپلود',
    ],
    'Calculate' => [
        'en-us' => 'Calculate',
        'zh-cn' => '計算',
    ],
    'UpFileTooLarge' => [
        'en-us' => 'The File is too Large!',
        'zh-cn' => '文件過大，終止上傳。',
        'ja' => '超えると、アップロードは終了します。',
        'ko-kr' => '파일이 너무 커서 업로드가 종료되었습니다.',
        'fa' => 'فایل خیلی بزرگ است!',
    ],
    'UploadStart' => [
        'en-us' => 'Upload Start',
        'zh-cn' => '開始上傳',
        'ja' => 'アップロードを開始',
        'ko-kr' => '업로드 시작',
        'fa' => 'شروع آپلود',
    ],
    'UploadStartAt' => [
        'en-us' => 'Start At',
        'zh-cn' => '開始於',
        'ja' => 'で開始',
        'ko-kr' => '에서 시작',
        'fa' => 'شروع از',
    ],
    'ThisTime' => [
        'en-us' => 'This Time',
        'zh-cn' => '本次',
        'ja' => '今回は',
        'ko-kr' => '이번에는',
        'fa' => 'این زمان',
    ],
    'LastUpload' => [
        'en-us' => 'Last time Upload',
        'zh-cn' => '上次上傳',
        'ja' => '上回は',
        'ko-kr' => '마지막 업로드',
        'fa' => 'آخرین زمان آپلود',
    ],
    'AverageSpeed' => [
        'en-us' => 'AverageSpeed',
        'zh-cn' => '平均速度',
        'ja' => '平均速度',
        'ko-kr' => '평균 속도',
        'fa' => 'میانگین سرعت',
    ],
    'CurrentSpeed' => [
        'en-us' => 'CurrentSpeed',
        'zh-cn' => '即時速度',
        'ja' => 'インスタントスピード',
        'ko-kr' => '즉각적인 속도',
        'fa' => 'سرعت فعلی',
    ],
    'Expect' => [
        'en-us' => 'Expect',
        'zh-cn' => '預計還要',
        'ja' => '期待される',
        'ko-kr' => '예상',
        'fa' => 'انتظار',
    ],
    'EndAt' => [
        'en-us' => 'End At',
        'zh-cn' => '結束於',
        'ja' => 'で終了',
        'ko-kr' => '에 끝남',
        'fa' => 'پایان از',
    ],
    'UploadErrorUpAgain' => [
        'en-us' => 'Maybe error, do upload again.',
        'zh-cn' => '可能出錯，重新上傳。',
        'ja' => '間違っている可能性があります。もう一度アップロードしてください。',
        'ko-kr' => '잘못되었을 수 있습니다. 다시 업로드하십시오.',
        'fa' => 'خطا، دوباره آپلود کنید',
    ],
    'UploadComplete' => [
        'en-us' => 'Upload Complete',
        'zh-cn' => '上傳完成',
        'ja' => 'アップロード完了',
        'ko-kr' => '업로드 완료',
        'fa' => 'آپلود با موفقیت انجام شد',
    ],
    'UploadFail23' => [
        'en-us' => 'Upload Fail, contain #.',
        'zh-cn' => '目錄或文件名含有#，上傳失敗。',
        'ja' => 'ディレクトリまたはファイル名に＃が含まれています。アップロードに失敗しました。',
        'ko-kr' => '디렉토리 또는 파일 이름에 #이 포함되어 있습니다. 업로드하지 못했습니다.',
        'fa' => 'بارگذاری ناموفق، حاوی #.',
    ],
    'defaultSitename' => [
        'en-us' => 'OneManager',
    ],
    'SavingToken' => [
        'en-us' => 'Saving refresh_token!',
        'zh-cn' => '正在保存 refresh_token！',
        'ja' => 'refresh_tokenを保存しています！',
        'ko-kr' => 'refresh_token 저장 중!',
        'fa' => 'در حال ذخیره refresh_token!',
    ],
    'MayinEnv' => [
        'en-us' => 'The \'Drive_ver\' may in Config',
        'zh-cn' => 'Drive_ver應該已經寫入',
        'ja' => 'Drive_verは環境変數に書き込まれている必要があります',
        'ko-kr' => 'Drive_verが書き込まれている必要があります',
        'fa' => 'The \'Drive_ver\' may in Config',
    ],
    'Wait' => [
        'en-us' => 'Wait',
        'zh-cn' => '稍等',
        'ja' => 'ちょっと待って',
        'ko-kr' => '잠깐만',
        'fa' => 'منتظر بمانید',
    ],
    'WaitJumpIndex' => [
        'en-us' => 'Wait 5s jump to Home page',
        'zh-cn' => '等5s跳到首頁',
        'ja' => '5秒待ってホームページにジャンプします',
        'ko-kr' => '5 초 동안 홈페이지로 이동',
        'fa' => '۵ دقیقه صبر کنید تا به صفحه نخست برگردید',
    ],
    'JumptoOffice' => [
        'en-us' => 'Login Office and Get a refresh_token',
        'zh-cn' => '跳轉到Office，登入獲取refresh_token',
        'ja' => 'Officeにジャンプしてログインし、refresh_tokenを取得します',
        'ko-kr' => '사무실로 이동하여 로그인하여 refresh_token을 받으십시오.',
        'fa' => 'وارد Office شوید و یک refresh_token دریافت کنید',
    ],
    'OnedriveDiskTag' => [
        'en-us' => 'Onedrive Disk Tag',
        'zh-cn' => 'Onedrive 標簽',
        'ja' => 'Onedriveタグ',
        'ko-kr' => 'Onedrive 태그',
        'fa' => 'برچسب دیسک Onedrive',
    ],
    'OnedriveDiskName' => [
        'en-us' => 'Onedrive Showed Name',
        'zh-cn' => 'Onedrive 顯示名稱',
        'ja' => 'Onedrive表示名',
        'ko-kr' => 'Onedrive 표시 이름',
        'fa' => 'نام نشان داده شده Onedrive',
    ],
    'DriveVerMS' => [
        'en-us' => 'Onedrive, Onedrive for business',
        'zh-cn' => '國際版（商業版與個人版）',
    ],
    'DriveVerCN' => [
        'en-us' => 'Onedrive in China',
        'zh-cn' => '世紀互聯版',
        'ja' => ' のOnedrive',
        'ko-kr' => '중국 Onedrive',
        'fa' => 'Onedrive در چین',
    ],
    'DriveVerShareurl' => [
        'en-us' => 'A share link of a folder',
        'zh-cn' => '共享連結',
    ],
    'UseShareLink' => [
        'en-us' => 'Share a folder in Onedrive (enable EDIT for everyone), input the link url below.',
        'zh-cn' => '對一個Onedrive文件夾共享，允許所有人編輯，然後将共享連結填在下方',
    ],
    'CustomIdSecret' => [
        'en-us' => 'Use custom client id & secret instead of OneManager default',
        'zh-cn' => '自己申請應用ID與機密，不用OneManager預設的',
        'ja' => 'アプリケーションIDとシークレットを自分で申請する',
        'ko-kr' => '응용 프로그램 ID 및 비밀 신청',
        'fa' => 'به طور پیش فرض اما از شناسه برنامه و سکرت استفاده کنید',
    ],
    'GetSecretIDandKEY' => [
        'en-us' => 'Get custom client id & secret',
        'zh-cn' => '申請應用ID與機密',
        'ja' => 'アプリケーションIDとシークレット',
        'fa' => 'دریافت شناسه برنامه و سکرت',
    ],
    'UseSharepointInstead' => [
        'en-us' => 'Use space in Sharepoint website instead of Onedrive',
        'zh-cn' => '使用Sharepoint網站的空間，不使用Onedrive',
    ],
    'GetSharepointSiteAddress' => [
        'en-us' => 'Login office.com and click the SharePoint, create a website or find an exist website, input the Site address below',
        'zh-cn' => '登入office.com，點擊Sharepoint，創建一個網站（或使用原有網站），然後将它的站點網址填在下方',
    ],
    'InputSharepointSiteAddress' => [
        'en-us' => 'https://xxxxx.sharepoint.com/sites(teams)/{name}',
    ],
    'TagFormatAlert' => [
        'en-us' => 'Tag must start with a letter, end with a letter or digit and can only contain lowercase letters, digits, and dashes， at least 2 letters!',
        'zh-cn' => '標簽只能以字母開頭，以字母或數字結尾，至少2位',
        'ja' => 'タグは、文字で始まり、文字または數字で終わる必要があります。少なくとも2つ',
        'ko-kr' => '태그는 문자로 시작하고 문자 또는 숫자로 끝나야합니다 (2 이상).',
        'fa' => 'برچسب باید با یک حرف شروع شود، با یک حرف یا رقم پایان یابد و تنها می‌تواند حاوی حروف کوچک، ارقام و خط فاصله، حداقل ۲ حرف باشد!',
    ],
    'ClickInstall' => [
        'en-us' => 'Click to install the project',
        'zh-cn' => '點擊開始安裝程式',
        'ja' => 'クリックしてインストールプロセスを開始します',
        'ko-kr' => '설치 과정을 시작하려면 클릭',
        'fa' => 'برای نصب پروژه کلیک کنید',
    ],
    'LogintoBind' => [
        'en-us' => 'then login and bind your onedrive in setup',
        'zh-cn' => '然後登入後在設置中綁定你的onedrive。',
        'ja' => '次に、ログインして、設定でonedriveをバインドします。',
        'ko-kr' => '그런 다음 로그인하여 onedrive를 설정에 바인딩하십시오.',
        'fa' => 'پس از آن وارد سیستم شوید و تنظیمات خود را در onedrive متصل کنید',
    ],
    'MakesuerWriteable' => [
        'en-us' => 'Plase make sure the config.php is writeable. run writeable.sh.',
        'zh-cn' => '确認config.php可寫。',
        'ja' => 'config.phpが書き込み可能であることを確認してください。',
        'ko-kr' => 'config.php가 쓰기 가능한지 확인하십시오.',
        'fa' => 'اطمینان حاصل کنید که config.php قابل نوشتن است. writeable.sh را اجرا کنید.',
    ],
    'MakesuerRewriteOn' => [
        'en-us' => 'Plase make sure the RewriteEngine is On.',
        'zh-cn' => '确認重寫（僞靜态）功能啓用。',
        'ja' => '書き換え（擬似靜的）機能が有効になっていることを確認します。',
        'ko-kr' => '다시 쓰기 (의사 정적) 기능이 활성화되어 있는지 확인하십시오.',
        'fa' => 'لطفاً مطمئن شوید که RewriteEngine روشن است.',
    ],
    'CopyUrl' => [
        'en-us' => 'Copy URL',
        'zh-cn' => '複制連結',
    ],
    'Success' => [
        'en-us' => 'Success',
        'zh-cn' => '成功',
    ],
    'SetAdminPassword' => [
        'en-us' => 'Set Admin Password',
        'zh-cn' => '設置管理密碼',
    ],
    'Refresh' => [
        'en-us' => 'Refresh',
        'zh-cn' => '重新整理',
        'ja' => 'リフレッシュ',
        'ko-kr' => '새로 고침',
        'fa' => 'رفرش',
    ],
    'SelectLanguage' => [
        'en-us' => 'Select Language',
        'zh-cn' => '選擇語言',
        'ja' => '言語を選択してください',
        'ko-kr' => '언어를 선택하십시오',
        'fa' => 'زبان را انتخاب کنید',
    ],
    'RefreshCache' => [
        'en-us' => 'RefreshCache',
        'zh-cn' => '重新整理快取',
        'ja' => 'キャッシュを再構築',
        'ko-kr' => '캐시 플러시',
        'fa' => 'رفرش cache',
    ],
    'CannotOneKeyUpate' => [
        'en-us' => 'Can not update by a click! run update.sh',
        'zh-cn' => '不能一鍵更新，可以運作update.sh',
    ],
    'QueryBranchs' => [
        'en-us' => 'Query Branchs',
        'zh-cn' => '查詢分支',
    ],
    'ONEMANAGER_CONFIG_SAVE_ENV' => [
        'en-us' => 'Config save in Environments',
        'zh-cn' => '配置保存在環境變量',
    ],
    'ONEMANAGER_CONFIG_SAVE_FILE' => [
        'en-us' => 'Config save in code file, may cause fee',
        'zh-cn' => '配置保存在代碼文件中，可能産生費用',
    ],
];